baseurl = "/"
languageCode = "en-us"
title = "B. Ogan Mancarci"
theme = "hugo-lithium"
googleAnalytics = "UA-111816736-3"
# disqusShortname = "oganm/oganm.com"
hede = "oganm/oganm.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
enableEmoji = false


[permalinks]
    post = "/:slug/"


[[menu.main]]
	name = ""
	identifier = "github"
    pre = "<i class='fab fa-github'></i>"
    url = "https://github.com/oganm"
    weight = 1
[[menu.main]]
	name = ""
	identifier = "twitter"
    pre = "<i class='fab fa-twitter'></i>"
    url = "https://twitter.com/oganm"
    weight = 2
[[menu.main]]
	name = ""
	identifier = "mail"
    pre = "<i class='fas fa-at'></i>"
    url = "mailto:ogan.mancarci@gmail.com"
    weight = 3
[[menu.main]]
	name = "Publications"
	identifier = "scholar"
    pre = "<i class='fas fa-graduation-cap' aria-hidden></i>"
    url = "https://scholar.google.ca/citations?user=4PWiDJgAAAAJ&hl=en"
    weight = 4
[[menu.main]]
	pre = "&nbsp;"
    name = "Tools"
    identifier = "worktools"
    weight = 5
[[menu.main]]
	pre = "&nbsp;"
    name = "Fun tools"
    identifier = "funtools"
    weight = 6
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 7
    url = "/post/"
[[menu.main]]
	name = "NeuroExpresso"
	parent = "worktools"
	url = "http://neuroexpresso.org"
	weight = 1
[[menu.main]]
	name = "5e char sheet printer"
	parent = "funtools"
	url = "https://oganm.com/shiny/printSheetApp"
	weight = 2
[[menu.main]]
	name = "5e interactive sheet"
	parent = "funtools"
	url = "https://oganm.com/shiny/interactiveSheet/"
	weight = 1
[[menu.main]]
	name = "Swarm Simulator"
	parent = "funtools"
	url = "https://oganm.com/shiny/swarm/"
	weight = 3
[[menu.main]]
	name = "Notes to self"
	parent = "blog"
	weight = 3
	url = "/categories/notes-to-self/"
[[menu.main]]
	name = "Code"
	parent = "blog"
	weight = 1
	url = "/categories/Code/"
[[menu.main]]
	name = "Other"
	parent = "blog"
	weight = 2
	url = "/categories/other/"

[params]
    description = "Personal blog of Ogan Mancarci"
    author = "Ogan Mancarci"
	customCSS = ["css/dropdown.css?v=1","css/navbarcolors.css?v=1","css/mainoverwrite.css?v=1","css/misc.css"]
	preCSS = ["css/grid12.css"]
	utterances = "oganm/oganm.com"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"


    [params.logo]
    url = "ogbrain.jpg"
    title = ""
    width = 50
    height = 50
    alt = "Logo"

